## code to prepare `df_route_unclean` dataset goes here

df_route_unclean <-
  tibble::tribble(
    ~orig_city, ~orig_state, ~orig_zip, ~orig_ctry, ~dest_city, ~dest_state, ~dest_zip, ~dest_ctry, ~bad_introduced,
    "STONEY CREEK", "ON", "L8E2B4", "CA", "SAINT-LAURENT", "QC", "H4R0M6", "CAN", "Dest ctry modified",
    "BRAMPTON", "ON", "L6S6C8", "CAD", "BOUCHERVILLE", "QC", "J4B7M7", "CA", "Orig ctry modified badly",
    "STONEY CREEK", "ON", "L8E2B4", "CA", "ALLISTON", "ON", "L9R2A9", "CA", NA,
    "STONEY CREEK", "ON", "L8E2B4", "CA", "VICTORIA", "BC", "V9B4V5", "CA", NA,
    "STONEY CREEK", "ON", "L8E2B4", "CA", "GATINEAU", "QC", "J8Z1T3", "CA", NA,
    "STONEY CREEK", "ON", "L8E2B4", "CA", "CHILLIWACK", "BC", "V2R5M4", "CA", NA,
    "STONEY CREEK", "ON", "L8E2B4", "CA", "EDMONTON", "AB", "T5E5R8", "CA", NA,
    "STONEY CREEK", "ON", "L8E2B4", "CA", "COURTENAY", "BC", "V9N2L9", "CA", NA,
    "BRAMPTON", "ON", "L6S6C8", "CA", "SOUTHAMPTON", "ON", "N0H", "CA", "Dest postal is partial only",
    "STONEY CREEK", "ON", "L8E2B4", "CA", "MONT-TREMBLANT", "QC", "J8E3J9", "CA", NA,
    "STONEY CREEK", "ON", "L8E2B4", "CA", "VAUGHAN", "ON", "L4H4P9", "CA", NA,
    "BRAMPTON", "ON", "L6S6E9", "CA", "GUADALUPE", "NL", "67110", "MX", NA,
    "BRAMPTON", "ON", "L6S6E9", "CA", "SALINAS VICTORIA", "NL", "66616", "MX", NA,
    "MISSISSAUGA", "ON", "L5S2A4", "CA", "AURORA", "IL", "60506", "US", NA,
    "HAMILTON", "ON", "L8S3C3", "CA", "FAIRBURN", "GA", "30213", "US", NA,
    "SCARBOROUGH", "ON", "M1P2Z4", "CA", "AURORA", "IL", "60506", "US", NA,
    "STONEY CREEK", "ON", "L8E", "CA", "LOVES PARK", "IL", "61111", "US", "Orig postal is partial only",
    "HAMILTON", "ON", "L8L8K6", "CA", "ONTARIO", "CA", "91761", "US", NA,
    "GUELPH", "ON", "N1G3R3", "CA", "AURORA", "IL", "60506", "US", NA,
    "TORONTO", "ON", "M1R4G2", "CA", "EDISON", "NJ", "8817", "US", "Dest zip removed leading 0",
    "HAMILTON", "ON", "L8L8K6", "CA", "AURORA", "IL", "60506", "US", NA,
    "TORONTO", "ON", "M4B2T7", "CA", "PORTLAND", "OR", "97203", "US", NA,
    "STONEY CREEK", "ON", "L8E2B4", "CA", "ONTARIO", "CA", "91761", "US", NA,
    "HAMILTON", "ON", "L8L8K6", "CA", "FAIRBURN", "GA", "30213", "US", NA,
    "ZAPOPAN", "JAL", "45134", "MX", "STONEY CREEK", "ON", "L8E2B4", "CA", NA,
    "GUADALUPE", "NL", "67110", "MX", "BRAMPTON", "ON", "L6S6C8", "CA", NA,
    "SALINAS VICTORIA", "NL", "66616", "MX", "STONEY CREEK", "ON", "L8E2B4", "CA", NA,
    "GUADALUPE", "NL", "67110", "MX", "STONEY CREEK", "ON", "L8E2B4", "CA", NA,
    "SALINAS VICTORIA", "NL", "66616", "MX", "BRAMPTON", "ON", "L6S6C8", "CA", NA,
    "GUADALUPE", "NL", "67110", "MX", "SALINAS VICTORIA", "NL", "66616", "MX", NA,
    "SALINAS VICTORIA", "NL", "66616", "MX", "MONROE", "NJ", "08831", "US", NA,
    "SALINAS VICTORIA", "NL", "66616", "MX", "HAVERHILL", "MA", "1835", "US", "Dest zip removed leading 0",
    "SALINAS VICTORIA", "NL", "66616", "MX", "TULSA", "OK", "74145", "US", NA,
    "SALINAS VICTORIA", "NL", "66616", "MX", "PORTLAND", "OR", "97217", "US", NA,
    "SALINAS VICTORIA", "NL", "66616", "MX", "GRANDVILLE", "MI", "49418", "US", NA,
    "SALINAS VICTORIA", "NL", "66616", "MEX", "EASTON", "PA", "18045", "US", "Orig ctry is MEX",
    "SALINAS VICTORIA", "NL", "66616", "MX", "ST GEORGE", "UT", "84790", "US", NA,
    "SALINAS VICTORIA", "NL", "66616", "MX", "SEARCY", "AR", "72143", "US", NA,
    "SALINAS VICTORIA", "NL", "66616", "MX", "JONESVILLE", "SC", "29353", "US", NA,
    "SALINAS VICTORIA", "NL", "66616", "MX", "MORRIS", "IL", "60450", "US", NA,
    "SALINAS VICTORIA", "NL", "66616", "MX", "LAS VEGAS", "NV", "89115", "US", NA,
    "ELK GROVE VILLAGE", "IL", "60007", "US", "BRAMPTON", "ON", "L6S6C8", "CA", NA,
    "CALUMET CITY", "IL", "60409", "US", "SCARBOROUGH", "ON", "M1P2Z4", "CA", NA,
    "SAINT CLAIR", "MI", "48079", "US", "TORONTO", "ON", "M4B2T7", "CA", NA,
    "CARLISLE", "PA", "17015", "US", "TORONTO", "ON", "M6J3L9", "CA", NA,
    "INDIANAPOLIS", "IN", "46219", "US", "TORONTO", "ON", "M1L2P6", "CA", NA,
    "CARLISLE", "PA", "17015", "US", "CONCORD", "ON", "L4K3C4", "CA", NA,
    "MILFORD", "PA", "18337", "US", "BRAMPTON", "ON", "L6S6C8", "CA", NA,
    "CARLISLE", "PA", "17015", "US", "WOODBRIDGE", "ON", "L4H3N5", "CA", NA,
    "ROCKFORD", "IL", "61109", "U.S.", "BRAMPTON", "ON", "L6S6C8", "CA", "Orig ctry is U.S.",
    "BURLINGTON", "IA", "52601", "US", "BRAMPTON", "ON", "L6S6C8", "CA", NA,
    "TETERBORO", "NJ", "7608", "US", "TORONTO", "ON", "M1L2P6", "CA", "Orig zip removed leading 0",
    "TOLEDO", "OH", "43605", "US", "SALINAS VICTORIA", "NL", "66616", "MX", NA,
    "DAYTON", "NJ", "8810", "US", "SALINAS VICTORIA", "NL", "66616", "MX", "Orig zip removed leading 0",
    "BALTIMORE", "MD", "21224", "US", "SALINAS VICTORIA", "NL", "66616", "MX", NA,
    "TOLEDO", "OH", "43940", "US", "SALINAS VICTORIA", "NL", NA, "MX", "Dest zip missing",
    "OTTAWA", "IL", "61350", "US", "SALINAS VICTORIA", "NL", "66616", "MX", NA,
    "FRESNO", "CA", "93702", "US", "GUADALUPE", "NL", "67110", "MX", NA,
    "GRANT PARK", "IL", "60940", "US", "SALINAS VICTORIA", "NL", "66616", "MX", NA,
    "SANTA ROSA", "CA", "95401", "US", "GUADALUPE", "NL", "67110", "MX", NA,
    "LONDON", "KY", "40744", "US", "SALINAS VICTORIA", "NL", "66616", "MX", NA,
    "QUINCY", "IL", "62301", "US", "GUADALUPE", "NL", "67110", "MX", NA,
    "MICHIGAN CITY", NA, "46360", "US", "SALINAS VICTORIA", "NL", "66616", "MX", "Orig state missing",
    "CARLISLE", "PA", "17015", "USA", "PORT CHARLOTTE", "FL", "33948", "US", "Orig ctry is USA",
    "SHIRLEY", "NY", "11967", "US", "FAIRBURN", "GA", "30213", "US", NA,
    "CARLISLE", "PA", "17015", "US", "DEKALB", "IL", "60115", "US", NA,
    "WEST CHESTER", "OH", "45011", "US", "BEECH ISLAND", "SC", "29842", "US", NA,
    "HAMMOND", "LA", "70401", "US", "FAIRBURN", "GA", "30213", "US", NA,
    "AURORA", "IL", "60506", "US", "SANDERSVILLE", "GA", "31082", "US", NA,
    "ONTARIO", "CA", "91761", "US", "COEUR D ALENE", "ID", "83815", "US", NA,
    "AURORA", "IL", "60506", "US", "BELLWOOD", "IL", "60104", "US", NA,
    "CARLISLE", "PA", "17015", "US", "PHILADELPHIA", "PA", "19148", "US", NA,
    "LOVES PARK", "IL", "61111", "US", "HERMISTON", "OR", "97838", "US", NA,
    "LIVERMORE", "CA", "94551", "US", "ONTARIO", "CA", "91761", "US", NA
  )

usethis::use_data(df_route_unclean, overwrite = TRUE)
