## code to prepare `df_route_samples` dataset goes here

df_route_samples <-
  tibble::tribble(
          ~orig_city, ~orig_state, ~orig_zip, ~orig_ctry,         ~dest_city, ~dest_state, ~dest_zip, ~dest_ctry,
      "STONEY CREEK",        "ON",  "L8E2B4",       "CA",    "SAINT-LAURENT",        "QC",  "H4R0M6",       "CA",
          "BRAMPTON",        "ON",  "L6S6C8",       "CA",     "BOUCHERVILLE",        "QC",  "J4B7M7",       "CA",
      "STONEY CREEK",        "ON",  "L8E2B4",       "CA",         "ALLISTON",        "ON",  "L9R2A9",       "CA",
      "STONEY CREEK",        "ON",  "L8E2B4",       "CA",         "VICTORIA",        "BC",  "V9B4V5",       "CA",
      "STONEY CREEK",        "ON",  "L8E2B4",       "CA",         "GATINEAU",        "QC",  "J8Z1T3",       "CA",
      "STONEY CREEK",        "ON",  "L8E2B4",       "CA",       "CHILLIWACK",        "BC",  "V2R5M4",       "CA",
      "STONEY CREEK",        "ON",  "L8E2B4",       "CA",         "EDMONTON",        "AB",  "T5E5R8",       "CA",
      "STONEY CREEK",        "ON",  "L8E2B4",       "CA",        "COURTENAY",        "BC",  "V9N2L9",       "CA",
          "BRAMPTON",        "ON",  "L6S6C8",       "CA",      "SOUTHAMPTON",        "ON",  "N0H2L0",       "CA",
      "STONEY CREEK",        "ON",  "L8E2B4",       "CA",   "MONT-TREMBLANT",        "QC",  "J8E3J9",       "CA",
      "STONEY CREEK",        "ON",  "L8E2B4",       "CA",          "VAUGHAN",        "ON",  "L4H4P9",       "CA",
          "BRAMPTON",        "ON",  "L6S6E9",       "CA",        "GUADALUPE",        "NL",   "67110",       "MX",
          "BRAMPTON",        "ON",  "L6S6E9",       "CA", "SALINAS VICTORIA",        "NL",   "66616",       "MX",
       "MISSISSAUGA",        "ON",  "L5S2A4",       "CA",           "AURORA",        "IL",   "60506",       "US",
          "HAMILTON",        "ON",  "L8S3C3",       "CA",         "FAIRBURN",        "GA",   "30213",       "US",
       "SCARBOROUGH",        "ON",  "M1P2Z4",       "CA",           "AURORA",        "IL",   "60506",       "US",
      "STONEY CREEK",        "ON",  "L8E2B4",       "CA",       "LOVES PARK",        "IL",   "61111",       "US",
          "HAMILTON",        "ON",  "L8L8K6",       "CA",          "ONTARIO",        "CA",   "91761",       "US",
            "GUELPH",        "ON",  "N1G3R3",       "CA",           "AURORA",        "IL",   "60506",       "US",
           "TORONTO",        "ON",  "M1R4G2",       "CA",           "EDISON",        "NJ",   "08817",       "US",
          "HAMILTON",        "ON",  "L8L8K6",       "CA",           "AURORA",        "IL",   "60506",       "US",
           "TORONTO",        "ON",  "M4B2T7",       "CA",         "PORTLAND",        "OR",   "97203",       "US",
      "STONEY CREEK",        "ON",  "L8E2B4",       "CA",          "ONTARIO",        "CA",   "91761",       "US",
          "HAMILTON",        "ON",  "L8L8K6",       "CA",         "FAIRBURN",        "GA",   "30213",       "US",
           "ZAPOPAN",       "JAL",   "45134",       "MX",     "STONEY CREEK",        "ON",  "L8E2B4",       "CA",
         "GUADALUPE",        "NL",   "67110",       "MX",         "BRAMPTON",        "ON",  "L6S6C8",       "CA",
  "SALINAS VICTORIA",        "NL",   "66616",       "MX",     "STONEY CREEK",        "ON",  "L8E2B4",       "CA",
         "GUADALUPE",        "NL",   "67110",       "MX",     "STONEY CREEK",        "ON",  "L8E2B4",       "CA",
  "SALINAS VICTORIA",        "NL",   "66616",       "MX",         "BRAMPTON",        "ON",  "L6S6C8",       "CA",
         "GUADALUPE",        "NL",   "67110",       "MX", "SALINAS VICTORIA",        "NL",   "66616",       "MX",
  "SALINAS VICTORIA",        "NL",   "66616",       "MX",           "MONROE",        "NJ",   "08831",       "US",
  "SALINAS VICTORIA",        "NL",   "66616",       "MX",        "HAVERHILL",        "MA",   "01835",       "US",
  "SALINAS VICTORIA",        "NL",   "66616",       "MX",            "TULSA",        "OK",   "74145",       "US",
  "SALINAS VICTORIA",        "NL",   "66616",       "MX",         "PORTLAND",        "OR",   "97217",       "US",
  "SALINAS VICTORIA",        "NL",   "66616",       "MX",       "GRANDVILLE",        "MI",   "49418",       "US",
  "SALINAS VICTORIA",        "NL",   "66616",       "MX",           "EASTON",        "PA",   "18045",       "US",
  "SALINAS VICTORIA",        "NL",   "66616",       "MX",        "ST GEORGE",        "UT",   "84790",       "US",
  "SALINAS VICTORIA",        "NL",   "66616",       "MX",           "SEARCY",        "AR",   "72143",       "US",
  "SALINAS VICTORIA",        "NL",   "66616",       "MX",       "JONESVILLE",        "SC",   "29353",       "US",
  "SALINAS VICTORIA",        "NL",   "66616",       "MX",           "MORRIS",        "IL",   "60450",       "US",
  "SALINAS VICTORIA",        "NL",   "66616",       "MX",        "LAS VEGAS",        "NV",   "89115",       "US",
 "ELK GROVE VILLAGE",        "IL",   "60007",       "US",         "BRAMPTON",        "ON",  "L6S6C8",       "CA",
      "CALUMET CITY",        "IL",   "60409",       "US",      "SCARBOROUGH",        "ON",  "M1P2Z4",       "CA",
       "SAINT CLAIR",        "MI",   "48079",       "US",          "TORONTO",        "ON",  "M4B2T7",       "CA",
          "CARLISLE",        "PA",   "17015",       "US",          "TORONTO",        "ON",  "M6J3L9",       "CA",
      "INDIANAPOLIS",        "IN",   "46219",       "US",          "TORONTO",        "ON",  "M1L2P6",       "CA",
          "CARLISLE",        "PA",   "17015",       "US",          "CONCORD",        "ON",  "L4K3C4",       "CA",
           "MILFORD",        "PA",   "18337",       "US",         "BRAMPTON",        "ON",  "L6S6C8",       "CA",
          "CARLISLE",        "PA",   "17015",       "US",       "WOODBRIDGE",        "ON",  "L4H3N5",       "CA",
          "ROCKFORD",        "IL",   "61109",       "US",         "BRAMPTON",        "ON",  "L6S6C8",       "CA",
        "BURLINGTON",        "IA",   "52601",       "US",         "BRAMPTON",        "ON",  "L6S6C8",       "CA",
         "TETERBORO",        "NJ",   "07608",       "US",          "TORONTO",        "ON",  "M1L2P6",       "CA",
            "TOLEDO",        "OH",   "43605",       "US", "SALINAS VICTORIA",        "NL",   "66616",       "MX",
            "DAYTON",        "NJ",   "08810",       "US", "SALINAS VICTORIA",        "NL",   "66616",       "MX",
         "BALTIMORE",        "MD",   "21224",       "US", "SALINAS VICTORIA",        "NL",   "66616",       "MX",
            "TOLEDO",        "OH",   "43940",       "US", "SALINAS VICTORIA",        "NL",   "66616",       "MX",
            "OTTAWA",        "IL",   "61350",       "US", "SALINAS VICTORIA",        "NL",   "66616",       "MX",
            "FRESNO",        "CA",   "93702",       "US",        "GUADALUPE",        "NL",   "67110",       "MX",
        "GRANT PARK",        "IL",   "60940",       "US", "SALINAS VICTORIA",        "NL",   "66616",       "MX",
        "SANTA ROSA",        "CA",   "95401",       "US",        "GUADALUPE",        "NL",   "67110",       "MX",
            "LONDON",        "KY",   "40744",       "US", "SALINAS VICTORIA",        "NL",   "66616",       "MX",
            "QUINCY",        "IL",   "62301",       "US",        "GUADALUPE",        "NL",   "67110",       "MX",
     "MICHIGAN CITY",        "IN",   "46360",       "US", "SALINAS VICTORIA",        "NL",   "66616",       "MX",
          "CARLISLE",        "PA",   "17015",       "US",   "PORT CHARLOTTE",        "FL",   "33948",       "US",
           "SHIRLEY",        "NY",   "11967",       "US",         "FAIRBURN",        "GA",   "30213",       "US",
          "CARLISLE",        "PA",   "17015",       "US",           "DEKALB",        "IL",   "60115",       "US",
      "WEST CHESTER",        "OH",   "45011",       "US",     "BEECH ISLAND",        "SC",   "29842",       "US",
           "HAMMOND",        "LA",   "70401",       "US",         "FAIRBURN",        "GA",   "30213",       "US",
            "AURORA",        "IL",   "60506",       "US",     "SANDERSVILLE",        "GA",   "31082",       "US",
           "ONTARIO",        "CA",   "91761",       "US",    "COEUR D ALENE",        "ID",   "83815",       "US",
            "AURORA",        "IL",   "60506",       "US",         "BELLWOOD",        "IL",   "60104",       "US",
          "CARLISLE",        "PA",   "17015",       "US",     "PHILADELPHIA",        "PA",   "19148",       "US",
        "LOVES PARK",        "IL",   "61111",       "US",        "HERMISTON",        "OR",   "97838",       "US",
         "LIVERMORE",        "CA",   "94551",       "US",          "ONTARIO",        "CA",   "91761",       "US"
 )

usethis::use_data(df_route_samples, overwrite = TRUE)
